### ISSUE TITLE
support for block comments 

### ISSUE THREAD

**Issue by htakatsuka** [jfcarter2358/jsonc#10]
Hi there, 

I  have just tried your module.
It would be awesome if you could add support for block comments
(just to be clear: comments starting with /* and ending with */ that
could span multiple lines). 

Thank you so much for your support!

**Comment by jfcarter2358** [comment]
Hello!

I've just merged in a PR which adds support for c-style block comments. If you want to give it a spin, try installing `jsoncparser==1.1.0` and let me know how that goes! There are some limitations currently to the support (I've listed them out in the PR [here](https://github.com/jfcarter2358/jsonc/pull/11)) but hopefully those won't be too much of an issue and they'll be taken care of as I re-work the backing parser.

**Comment by htakatsuka** [comment]
Thank you for your fast response!
I have tried it and it works!
