### ISSUE TITLE
Round trip support with comments ?

### ISSUE THREAD

**Issue by erwanp** [jfcarter2358/jsonc#2]
Hello @jfcarter2358 

I'm looking for a JSON parser with round-trip support for comments to use as a configuration file in [an open-source physics code](https://github.com/radis/radis). 

JSONC looks like a great candidate; and I can read JSON-with-comments files ; but I cannot edit the loaded dict then re-dump it.

Example : 

```python
import jsonc

jsonfilecontent = """{
"database": {                       # database key, stores all databases
    "HITEMP-CO2": {                 # a database name
    "path": [
        "PATH/TO/1",
        "PATH/TO/2"]}
  }
}"""

JSONCDict = jsonc.loads(jsonfilecontent )       # works fine!
with open("config.json", "w") as f:
    jsonc.dump(JSONCDict, f)     # works fine

# Now let's update the dict : 
JSONCDict['database']['NEW'] = {"path":"PATH/TO/3"}
# JSONCDict.refresh()           # tried with and without .refresh() here

with open("config.json", "w") as f:
    jsonc.dump(JSONCDict, f)     # fails to write a clean file (with .refresh() )  ; or doent change anything (without refresh)

# I get:
"""
{
"database": {                       # database key, stores all databases
    "HITEMP-CO2": {                    # a database name
    "path": [
        "PATH/TO/1",
        "PATH/TO/2"]}
  }
}        }                  👈  THIS WAS ADDED 
}                             👈  THIS TOO
}"""

Do you plan to support round-trip preservation of comments ? Can it be done already ? 

(note : we do not need to **add** comments through the code; but only preserve the human-added comments round-trip)

Best !

**Comment by jfcarter2358** [comment]
Hello! The current version of the parser attempts to use a diff of the dictionary before and after the edit to preserve comments, but it doesn't work very well at the moment and sometimes can break and lead to what you're seeing. I do have plans to implement a different and more robust mechanism into the project which should actually work this time around,  I'll try and get that implemented and tested this weekend at which point I'll upload a version 1.0.0 onto PyPI.

**Comment by erwanp** [comment]
Thanks for the fast answer; this would be very useful for us !!

**Comment by jfcarter2358** [comment]
@erwanp It took much longer than I expected but the new system is in place that supports roundtrip comments. If you update your requirements.txt to use `jsoncparser==1.0.0` and then re-install with pip that should solve the issues that you were seeing. Let me know if you run into anything else and I'll be happy to get them fixed. As a note, the whitespace between the JSON structure and the comment currently gets trimmed out and block comments are not supported, but I'll be adding both of those things soon in a 1.1.0 release.

**Comment by erwanp** [comment]
Just tested, and it works, well done ! 

@anandxkumar it will be very useful for RADIS users to add comments in the JSON config file https://github.com/radis/radis/issues/167
