### ISSUE TITLE
parsing fails if keys have comment-like symbols

### ISSUE THREAD

**Issue by erwanp** [jfcarter2358/jsonc#6]
Since #3 jsonc supports round-trip comments 👏  ; however it breaks if regular keys or values have `#` or `//` symbols 

Example :
```

import json
import jsonc

jsonfilecontent = r"""{
"key_1":"PATH_TO_",
"key_#2":"PATH_WITH_//_"
}"""

json.loads(jsonfilecontent )         # works fine!
jsonc.loads(jsonfilecontent )      # fails  because of "#" and "//" 

```

**Comment by jfcarter2358** [comment]
Great catch! I've just pushed version 1.0.1 to PyPI that fixes that and have updated the test cases to make sure it doesn't break in the future. Just run `pip install jsoncparser==1.0.1` to update your version and you should be in good shape.
