### ISSUE TITLE
Key named "key" are suppressed

### ISSUE THREAD

**Issue by erwanp** [jfcarter2358/jsonc#7]
```python

import jsonc

a = jsonc.loads("""{"key":"value"}""")
print(a)
>>> {}


a = jsonc.loads("""{"key2":"value"}""")
print(a)
>>> {'key2': 'value'}

```

Should at least raise an error if "key" is forbidden?

**Comment by jfcarter2358** [comment]
Great catch! It definitely should raise an exception. In addition, I've changed the protected keys (`'key`, `with_comments`, and `parent`) to all have the prefix `jsonc_`, so they should be a lot less likely to be set, but if they are a KeyError will be raised. I've uploaded version 1.0.2 to PyPI with this fix as well as updated the test cases to make sure that it doesn't come back as an issue.
