### ISSUE TITLE
JSONC fails simple printing when non-string keys are present

### ISSUE THREAD

**Issue by jfcarter2358** [jfcarter2358/jsonc#8]
As per [this](https://github.com/radis/radis/issues/328) issue in [radis](https://github.com/radis/radis) JSONC breaks when a PlainTextFormatter is applied against is when non-string keys are present in the dictionary.

**Comment by jfcarter2358** [comment]
@erwanp Version 1.0.3 is up in PyPI (install with `pip install jsoncparser==1.0.3`) and it should solve the issue you were seeing. Essentially some keywords that should have been changed had not been and it only really showed up with non-string keywords. Feel free to try the new version and let me know if you run into any other issues.

**Comment by erwanp** [comment]
Thank you !!
